// Code generated by ogen, DO NOT EDIT.
package api

type BookingsBookingIDGetRes interface {
	bookingsBookingIDGetRes()
}

type BookingsBookingIDPutRes interface {
	bookingsBookingIDPutRes()
}

type UsersLoginPostRes interface {
	usersLoginPostRes()
}

type UsersUserIDDeleteRes interface {
	usersUserIDDeleteRes()
}

type UsersUserIDGetRes interface {
	usersUserIDGetRes()
}
