// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// BookingsBookingIDGet implements GET /bookings/{bookingID} operation.
	//
	// Retrieve details of a specific booking by ID.
	//
	// GET /bookings/{bookingID}
	BookingsBookingIDGet(ctx context.Context, params BookingsBookingIDGetParams) (BookingsBookingIDGetRes, error)
	// BookingsBookingIDPut implements PUT /bookings/{bookingID} operation.
	//
	// Cancel an existing booking.
	//
	// PUT /bookings/{bookingID}
	BookingsBookingIDPut(ctx context.Context, params BookingsBookingIDPutParams) (BookingsBookingIDPutRes, error)
	// BookingsGet implements GET /bookings operation.
	//
	// Retrieve a list of all bookings that meets the conditions.
	//
	// GET /bookings
	BookingsGet(ctx context.Context, params BookingsGetParams) ([]Booking, error)
	// BookingsPost implements POST /bookings operation.
	//
	// Create a new booking for a live event.
	//
	// POST /bookings
	BookingsPost(ctx context.Context, req *NewBooking) (*Booking, error)
	// PingGet implements GET /ping operation.
	//
	// Check if the server is running.
	//
	// GET /ping
	PingGet(ctx context.Context) (*PingGetOK, error)
	// UsersLoginPost implements POST /users/login operation.
	//
	// Authenticate a user and generate a token.
	//
	// POST /users/login
	UsersLoginPost(ctx context.Context, req *LoginUser) (UsersLoginPostRes, error)
	// UsersPost implements POST /users operation.
	//
	// Register a new user with the system.
	//
	// POST /users
	UsersPost(ctx context.Context, req *NewUser) (*User, error)
	// UsersUserIDDelete implements DELETE /users/{userID} operation.
	//
	// Delete an existing user.
	//
	// DELETE /users/{userID}
	UsersUserIDDelete(ctx context.Context, params UsersUserIDDeleteParams) (UsersUserIDDeleteRes, error)
	// UsersUserIDGet implements GET /users/{userID} operation.
	//
	// Retrieve details of a specific user by ID.
	//
	// GET /users/{userID}
	UsersUserIDGet(ctx context.Context, params UsersUserIDGetParams) (UsersUserIDGetRes, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
