// Code generated by ogen, DO NOT EDIT.
package api

type BookingsBookingIdGetRes interface {
	bookingsBookingIdGetRes()
}

type BookingsBookingIdPutRes interface {
	bookingsBookingIdPutRes()
}

type UsersLoginPostRes interface {
	usersLoginPostRes()
}

type UsersUserIdDeleteRes interface {
	usersUserIdDeleteRes()
}

type UsersUserIdGetRes interface {
	usersUserIdGetRes()
}
