// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/uri"
)

// EncodeURI encodes BookingStatus as URI form.
func (s *BookingStatus) EncodeURI(e uri.Encoder) error {
	if err := e.EncodeField("status", func(e uri.Encoder) error {
		if val, ok := s.Status.Get(); ok {
			return e.EncodeValue(conv.StringToString(val))
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "encode field \"status\"")
	}
	return nil
}

var uriFieldsNameOfBookingStatus = [1]string{
	0: "status",
}

// DecodeURI decodes BookingStatus from URI form.
func (s *BookingStatus) DecodeURI(d uri.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode BookingStatus to nil")
	}

	if err := d.DecodeFields(func(k string, d uri.Decoder) error {
		switch k {
		case "status":
			if err := func() error {
				var sDotStatusVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					sDotStatusVal = c
					return nil
				}(); err != nil {
					return err
				}
				s.Status.SetTo(sDotStatusVal)
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"status\"")
			}
		default:
			return nil
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode BookingStatus")
	}

	return nil
}
