// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"
	"time"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/AuthToken
type AuthToken struct {
	// Authentication token.
	Token OptString `json:"token"`
}

// GetToken returns the value of Token.
func (s *AuthToken) GetToken() OptString {
	return s.Token
}

// SetToken sets the value of Token.
func (s *AuthToken) SetToken(val OptString) {
	s.Token = val
}

func (*AuthToken) usersLoginPostRes() {}

type BearerAuth struct {
	Token string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// Ref: #/components/schemas/Booking
type Booking struct {
	// Unique identifier for the booking.
	ID OptInt64 `json:"id"`
	// Name of the event.
	Name OptString `json:"name"`
	// Start date-time of the event.
	Start OptDateTime `json:"start"`
	// End date-time of the event.
	End OptDateTime `json:"end"`
	// User who made the booking.
	User   OptInt64         `json:"user"`
	Status OptBookingStatus `json:"status"`
	// Date and time when the booking was created.
	CreatedAt OptDateTime `json:"created_at"`
	// Date and time when the booking was last updated.
	UpdatedAt OptDateTime `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *Booking) GetID() OptInt64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *Booking) GetName() OptString {
	return s.Name
}

// GetStart returns the value of Start.
func (s *Booking) GetStart() OptDateTime {
	return s.Start
}

// GetEnd returns the value of End.
func (s *Booking) GetEnd() OptDateTime {
	return s.End
}

// GetUser returns the value of User.
func (s *Booking) GetUser() OptInt64 {
	return s.User
}

// GetStatus returns the value of Status.
func (s *Booking) GetStatus() OptBookingStatus {
	return s.Status
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Booking) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Booking) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Booking) SetID(val OptInt64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Booking) SetName(val OptString) {
	s.Name = val
}

// SetStart sets the value of Start.
func (s *Booking) SetStart(val OptDateTime) {
	s.Start = val
}

// SetEnd sets the value of End.
func (s *Booking) SetEnd(val OptDateTime) {
	s.End = val
}

// SetUser sets the value of User.
func (s *Booking) SetUser(val OptInt64) {
	s.User = val
}

// SetStatus sets the value of Status.
func (s *Booking) SetStatus(val OptBookingStatus) {
	s.Status = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Booking) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Booking) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

func (*Booking) bookingsBookingIDGetRes() {}
func (*Booking) bookingsBookingIDPutRes() {}

// Ref: #/components/schemas/BookingStatus
type BookingStatus struct {
	// New status for the booking.
	Status OptString `json:"status"`
}

// GetStatus returns the value of Status.
func (s *BookingStatus) GetStatus() OptString {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *BookingStatus) SetStatus(val OptString) {
	s.Status = val
}

// BookingsBookingIDGetNotFound is response for BookingsBookingIDGet operation.
type BookingsBookingIDGetNotFound struct{}

func (*BookingsBookingIDGetNotFound) bookingsBookingIDGetRes() {}

// BookingsBookingIDPutNotFound is response for BookingsBookingIDPut operation.
type BookingsBookingIDPutNotFound struct{}

func (*BookingsBookingIDPutNotFound) bookingsBookingIDPutRes() {}

// Represents error object.
// Ref: #/components/schemas/Error
type Error struct {
	Code    int64  `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int64 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int64) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/LoginUser
type LoginUser struct {
	// Email address of the user.
	Email OptString `json:"email"`
	// Password of the user.
	Password OptString `json:"password"`
}

// GetEmail returns the value of Email.
func (s *LoginUser) GetEmail() OptString {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *LoginUser) GetPassword() OptString {
	return s.Password
}

// SetEmail sets the value of Email.
func (s *LoginUser) SetEmail(val OptString) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *LoginUser) SetPassword(val OptString) {
	s.Password = val
}

// Ref: #/components/schemas/NewBooking
type NewBooking struct {
	// Name of the event.
	Name OptString `json:"name"`
	// Start date-time of the event.
	Start OptDateTime `json:"start"`
	// End date-time of the event.
	End OptDateTime `json:"end"`
	// User making the booking.
	User OptInt64 `json:"user"`
}

// GetName returns the value of Name.
func (s *NewBooking) GetName() OptString {
	return s.Name
}

// GetStart returns the value of Start.
func (s *NewBooking) GetStart() OptDateTime {
	return s.Start
}

// GetEnd returns the value of End.
func (s *NewBooking) GetEnd() OptDateTime {
	return s.End
}

// GetUser returns the value of User.
func (s *NewBooking) GetUser() OptInt64 {
	return s.User
}

// SetName sets the value of Name.
func (s *NewBooking) SetName(val OptString) {
	s.Name = val
}

// SetStart sets the value of Start.
func (s *NewBooking) SetStart(val OptDateTime) {
	s.Start = val
}

// SetEnd sets the value of End.
func (s *NewBooking) SetEnd(val OptDateTime) {
	s.End = val
}

// SetUser sets the value of User.
func (s *NewBooking) SetUser(val OptInt64) {
	s.User = val
}

// Ref: #/components/schemas/NewUser
type NewUser struct {
	// Full name of the user.
	Name OptString `json:"name"`
	// Email address of the user.
	Email OptString `json:"email"`
	// Password of the user.
	Password OptString `json:"password"`
}

// GetName returns the value of Name.
func (s *NewUser) GetName() OptString {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *NewUser) GetEmail() OptString {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *NewUser) GetPassword() OptString {
	return s.Password
}

// SetName sets the value of Name.
func (s *NewUser) SetName(val OptString) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *NewUser) SetEmail(val OptString) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *NewUser) SetPassword(val OptString) {
	s.Password = val
}

// NewOptBookingStatus returns new OptBookingStatus with value set to v.
func NewOptBookingStatus(v BookingStatus) OptBookingStatus {
	return OptBookingStatus{
		Value: v,
		Set:   true,
	}
}

// OptBookingStatus is optional BookingStatus.
type OptBookingStatus struct {
	Value BookingStatus
	Set   bool
}

// IsSet returns true if OptBookingStatus was set.
func (o OptBookingStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBookingStatus) Reset() {
	var v BookingStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBookingStatus) SetTo(v BookingStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBookingStatus) Get() (v BookingStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBookingStatus) Or(d BookingStatus) BookingStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type PingGetOK struct {
	// Response message.
	Message OptString `json:"message"`
}

// GetMessage returns the value of Message.
func (s *PingGetOK) GetMessage() OptString {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *PingGetOK) SetMessage(val OptString) {
	s.Message = val
}

// Ref: #/components/schemas/User
type User struct {
	// Unique identifier for the user.
	ID OptInt64 `json:"id"`
	// Full name of the user.
	Name OptString `json:"name"`
	// Email address of the user.
	Email OptString `json:"email"`
	// Password of the user (hashed).
	Password OptString `json:"password"`
	// Date and time when the user was created.
	CreatedAt OptDateTime `json:"created_at"`
	// Date and time when the user was last updated.
	UpdatedAt OptDateTime `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *User) GetID() OptInt64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *User) GetName() OptString {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *User) GetEmail() OptString {
	return s.Email
}

// GetPassword returns the value of Password.
func (s *User) GetPassword() OptString {
	return s.Password
}

// GetCreatedAt returns the value of CreatedAt.
func (s *User) GetCreatedAt() OptDateTime {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *User) GetUpdatedAt() OptDateTime {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *User) SetID(val OptInt64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *User) SetName(val OptString) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *User) SetEmail(val OptString) {
	s.Email = val
}

// SetPassword sets the value of Password.
func (s *User) SetPassword(val OptString) {
	s.Password = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *User) SetCreatedAt(val OptDateTime) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *User) SetUpdatedAt(val OptDateTime) {
	s.UpdatedAt = val
}

func (*User) usersUserIDGetRes() {}

// UsersLoginPostUnauthorized is response for UsersLoginPost operation.
type UsersLoginPostUnauthorized struct{}

func (*UsersLoginPostUnauthorized) usersLoginPostRes() {}

// UsersUserIDDeleteNoContent is response for UsersUserIDDelete operation.
type UsersUserIDDeleteNoContent struct{}

func (*UsersUserIDDeleteNoContent) usersUserIDDeleteRes() {}

// UsersUserIDDeleteNotFound is response for UsersUserIDDelete operation.
type UsersUserIDDeleteNotFound struct{}

func (*UsersUserIDDeleteNotFound) usersUserIDDeleteRes() {}

// UsersUserIDGetNotFound is response for UsersUserIDGet operation.
type UsersUserIDGetNotFound struct{}

func (*UsersUserIDGetNotFound) usersUserIDGetRes() {}
