// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// BookingsBookingIdDeleteParams is parameters of DELETE /bookings/{bookingId} operation.
type BookingsBookingIdDeleteParams struct {
	// ID of the booking to cancel.
	BookingId string
}

func unpackBookingsBookingIdDeleteParams(packed middleware.Parameters) (params BookingsBookingIdDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "bookingId",
			In:   "path",
		}
		params.BookingId = packed[key].(string)
	}
	return params
}

func decodeBookingsBookingIdDeleteParams(args [1]string, argsEscaped bool, r *http.Request) (params BookingsBookingIdDeleteParams, _ error) {
	// Decode path: bookingId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "bookingId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.BookingId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "bookingId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// BookingsBookingIdGetParams is parameters of GET /bookings/{bookingId} operation.
type BookingsBookingIdGetParams struct {
	// ID of the booking to retrieve.
	BookingId string
}

func unpackBookingsBookingIdGetParams(packed middleware.Parameters) (params BookingsBookingIdGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "bookingId",
			In:   "path",
		}
		params.BookingId = packed[key].(string)
	}
	return params
}

func decodeBookingsBookingIdGetParams(args [1]string, argsEscaped bool, r *http.Request) (params BookingsBookingIdGetParams, _ error) {
	// Decode path: bookingId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "bookingId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.BookingId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "bookingId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// BookingsBookingIdPutParams is parameters of PUT /bookings/{bookingId} operation.
type BookingsBookingIdPutParams struct {
	// ID of the booking to update.
	BookingId string
}

func unpackBookingsBookingIdPutParams(packed middleware.Parameters) (params BookingsBookingIdPutParams) {
	{
		key := middleware.ParameterKey{
			Name: "bookingId",
			In:   "path",
		}
		params.BookingId = packed[key].(string)
	}
	return params
}

func decodeBookingsBookingIdPutParams(args [1]string, argsEscaped bool, r *http.Request) (params BookingsBookingIdPutParams, _ error) {
	// Decode path: bookingId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "bookingId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.BookingId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "bookingId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UsersUserIdDeleteParams is parameters of DELETE /users/{userId} operation.
type UsersUserIdDeleteParams struct {
	// ID of the user to delete.
	UserId string
}

func unpackUsersUserIdDeleteParams(packed middleware.Parameters) (params UsersUserIdDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "userId",
			In:   "path",
		}
		params.UserId = packed[key].(string)
	}
	return params
}

func decodeUsersUserIdDeleteParams(args [1]string, argsEscaped bool, r *http.Request) (params UsersUserIdDeleteParams, _ error) {
	// Decode path: userId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "userId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.UserId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "userId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UsersUserIdGetParams is parameters of GET /users/{userId} operation.
type UsersUserIdGetParams struct {
	// ID of the user to retrieve.
	UserId string
}

func unpackUsersUserIdGetParams(packed middleware.Parameters) (params UsersUserIdGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "userId",
			In:   "path",
		}
		params.UserId = packed[key].(string)
	}
	return params
}

func decodeUsersUserIdGetParams(args [1]string, argsEscaped bool, r *http.Request) (params UsersUserIdGetParams, _ error) {
	// Decode path: userId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "userId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.UserId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "userId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
