// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// BookingsBookingIdDelete implements DELETE /bookings/{bookingId} operation.
//
// Cancel an existing booking.
//
// DELETE /bookings/{bookingId}
func (UnimplementedHandler) BookingsBookingIdDelete(ctx context.Context, params BookingsBookingIdDeleteParams) (r BookingsBookingIdDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BookingsBookingIdGet implements GET /bookings/{bookingId} operation.
//
// Retrieve details of a specific booking by ID.
//
// GET /bookings/{bookingId}
func (UnimplementedHandler) BookingsBookingIdGet(ctx context.Context, params BookingsBookingIdGetParams) (r BookingsBookingIdGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BookingsBookingIdPut implements PUT /bookings/{bookingId} operation.
//
// Update details of an existing booking.
//
// PUT /bookings/{bookingId}
func (UnimplementedHandler) BookingsBookingIdPut(ctx context.Context, req *UpdateBooking, params BookingsBookingIdPutParams) (r BookingsBookingIdPutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// BookingsGet implements GET /bookings operation.
//
// Retrieve a list of all bookings.
//
// GET /bookings
func (UnimplementedHandler) BookingsGet(ctx context.Context) (r []Booking, _ error) {
	return r, ht.ErrNotImplemented
}

// BookingsPost implements POST /bookings operation.
//
// Create a new booking for a live event.
//
// POST /bookings
func (UnimplementedHandler) BookingsPost(ctx context.Context, req *NewBooking) (r *Booking, _ error) {
	return r, ht.ErrNotImplemented
}

// PingGet implements GET /ping operation.
//
// Check if the server is running.
//
// GET /ping
func (UnimplementedHandler) PingGet(ctx context.Context) (r *PingGetOK, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersLoginPost implements POST /users/login operation.
//
// Authenticate a user and generate a token.
//
// POST /users/login
func (UnimplementedHandler) UsersLoginPost(ctx context.Context, req *LoginUser) (r UsersLoginPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersPost implements POST /users operation.
//
// Register a new user with the system.
//
// POST /users
func (UnimplementedHandler) UsersPost(ctx context.Context, req *NewUser) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersUserIdDelete implements DELETE /users/{userId} operation.
//
// Delete an existing user.
//
// DELETE /users/{userId}
func (UnimplementedHandler) UsersUserIdDelete(ctx context.Context, params UsersUserIdDeleteParams) (r UsersUserIdDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UsersUserIdGet implements GET /users/{userId} operation.
//
// Retrieve details of a specific user by ID.
//
// GET /users/{userId}
func (UnimplementedHandler) UsersUserIdGet(ctx context.Context, params UsersUserIdGetParams) (r UsersUserIdGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
