version: '3'

services:
  thirdbook-db:
    image: postgres:16.1
    container_name: thirdbook-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=thirdbook
    volumes:
      - local_thirdbook_volume:/var/lib/postgresql/data

volumes:
  local_thirdbook_volume:
