// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: for_test.sql

package rdb

import (
	"context"
)

const ping = `-- name: Ping :exec
select 1
`

func (q *Queries) Ping(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ping)
	return err
}
